#!/usr/bin/env python3

from setuptools import setup, find_packages

setup(
    name="rlvae",
    version="0.1.0",
    description="Riemannian Flow VAE for Longitudinal Data",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Antoine Laforgue",
    author_email="antoine.laforgue@etu.minesparis.psl.eu",
    url="https://github.com/antoinelfg/RlVAE",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "lightning>=2.0.0",
        "wandb>=0.15.0",
        "numpy>=1.21.0,<2.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.11.0",
        "scikit-learn>=1.0.0",
        "scikit-learn-extra",
        "tqdm>=4.62.0",
        "hydra-core>=1.2.0",
        "omegaconf>=2.2.0",
        "tensorboard>=2.9.0",
        "pandas>=1.3.0",
        "Pillow>=8.3.0",
        "kaleido",
    ],
    extras_require={
        "dev": [
            "black>=22.0.0",
            "isort>=5.10.0",
            "flake8>=4.0.0",
            "mypy>=0.950",
            "pytest>=7.0.0",
            "pytest-cov>=3.0.0",
            "pre-commit>=2.17.0",
        ],
        "docs": [
            "sphinx>=4.5.0",
            "sphinx-rtd-theme>=1.0.0",
            "myst-parser>=0.17.0",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Mathematics",
    ],
    keywords="variational-autoencoders, riemannian-geometry, deep-learning, pytorch, longitudinal-data",
) 