# Sample Configuration for Modular RlVAE
# =======================================
# This configuration demonstrates a typical setup for the VAE Research Platform

model:
  model_type: "modular_rlvae"
  latent_dim: 16
  input_dim: [3, 64, 64]
  n_flows: 5
  beta: 1.0
  riemannian_beta: 1.0
  posterior_type: "gaussian"
  encoder_arch: "cnn"
  decoder_arch: "cnn"
  sampling_method: "riemannian"

training:
  max_epochs: 50
  learning_rate: 0.0005
  batch_size: 32
  optimizer: "Adam"
  scheduler: "None"
  early_stopping: true
  gradient_clip: 1.0
  weight_decay: 0.0001
  validation_frequency: 1
  checkpoint_frequency: 5

data:
  dataset_type: "cyclic_sprites"
  num_sequences: 1000
  sequence_length: 20
  train_split: 0.8
  use_augmentation: false

visualization:
  level: "standard"
  plot_frequency: 5
  save_animations: false
  high_resolution: false