# @package _global_

# Main configuration for RlVAE experiments
defaults:
  - model: riemannian_flow_vae
  - training: default
  - data: cyclic_sprites
  - visualization: standard
  - experiment: single_run
  - _self_

# Experiment metadata
experiment_name: "rlvae_comparison"
project_name: "riemannian-vae-study"
description: "Systematic comparison of Riemannian geometry effects on VAE latent spaces"

# Global settings
seed: 42
device: "auto"  # auto, cpu, cuda
output_dir: "outputs"
wandb:
  project: "${project_name}"
  entity: null  # your wandb entity
  mode: "online"  # online, offline, disabled
  tags: []

# Hydra settings
hydra:
  run:
    dir: "${output_dir}/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}"
  sweep:
    dir: "${output_dir}/${experiment_name}/sweep_${now:%Y-%m-%d_%H-%M-%S}"
    subdir: "${hydra.job.num}" 