_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
batch_size:
    value: 1
beta:
    value: 1
cycle_penalty:
    value: 1
dataset_type:
    value: cyclic_only
experiment_type:
    value: Cyclic Sequences - Loop Mode OPEN
input_dim:
    value:
        - 3
        - 64
        - 64
latent_dim:
    value: 16
learning_rate:
    value: 0.0003
loop_mode:
    value: open
n_epochs:
    value: 1
n_flows:
    value: 8
posterior_type:
    value: riemannian_metric
riemannian_beta:
    value: 8
riemannian_method:
    value: geodesic
temperature_fix:
    value: 3
train_size:
    value: 2
use_riemannian:
    value: true
val_size:
    value: 2
