# @package model

_target_: models.modular_rlvae.ModularRiemannianFlowVAE

# Architecture
input_dim: [3, 64, 64]
latent_dim: 16
n_flows: 8
flow_hidden_size: 256
flow_n_blocks: 2
flow_n_hidden: 1
epsilon: 1e-6

# Encoder configuration - CNN
encoder:
  architecture: "cnn"
  layers: [32, 64, 128, 256]  # Number of channels per layer
  kernel_size: 3
  stride: 2
  padding: 1
  activation: "relu"
  batch_norm: true

# Decoder configuration - CNN
decoder:
  architecture: "cnn"
  layers: [256, 128, 64, 32]  # Number of channels per layer (reverse of encoder)
  kernel_size: 3
  stride: 2
  padding: 1
  output_padding: 1
  activation: "relu"
  batch_norm: true

# VAE parameters
beta: 1.0
riemannian_beta: 8.0

# Posterior configuration
posterior:
  type: "riemannian_metric"  # gaussian, iaf, riemannian_metric
  
# Sampling configuration
sampling:
  method: "geodesic"  # standard, basic, enhanced, geodesic, official
  use_riemannian: true
  
# Loop configuration
loop:
  mode: "open"  # open, closed
  penalty: 5.0
  
# Metric configuration
metric:
  path: "metric_T0.7_scaled.pt"
  temperature_override: 3.0
  
# Pretrained components
pretrained:
  encoder_path: "data/pretrained/encoder.pt"
  decoder_path: "data/pretrained/decoder.pt"
  metric_path: "data/pretrained/${model.metric.path}" 