# @package model

_target_: models.modular_rlvae.ModularRiemannianFlowVAE

# Architecture (same as Riemannian for fair comparison)
input_dim: [3, 64, 64]
latent_dim: 16
n_flows: 0  # No normalizing flows
flow_hidden_size: 256
flow_n_blocks: 2
flow_n_hidden: 1
epsilon: 1e-6

# VAE parameters
beta: 1.0
riemannian_beta: 0.0  # No Riemannian KL

# Posterior configuration
posterior:
  type: "gaussian"  # Standard Gaussian posterior
  
# Sampling configuration
sampling:
  method: "standard"  # Standard reparameterization
  use_riemannian: false
  
# Loop configuration
loop:
  mode: "open"  # Standard VAE doesn't handle loops
  penalty: 0.0
  
# Metric configuration (not used but for compatibility)
metric:
  path: "metric_T0.7_scaled.pt"
  temperature_override: 3.0
  
# Pretrained components
pretrained:
  encoder_path: "data/pretrained/encoder.pt"
  decoder_path: "data/pretrained/decoder.pt"
  metric_path: null  # No metric for vanilla VAE 